# Generated by Django 5.0 on 2023-12-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=80, verbose_name='Ingredients')),
                ('amount', models.IntegerField(verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Recipe name')),
                ('cooking_time', models.IntegerField(verbose_name='Cooking time')),
                ('cooking_method', models.TextField(verbose_name='Cooking method')),
                ('slug', models.SlugField(unique=True)),
                ('complexity', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, verbose_name='Complexity')),
                ('ingredients', models.ManyToManyField(related_name='Ingredients', to='book.ingredients')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
